### ISSUE TITLE
[error checking] doesn't detect when a DFA has multiple start states

### ISSUE THREAD

**Issue by CSchank** [CSchank/finsm#105]
I noticed this when I enabled (then disabled) a shortcut "s" on the build screen for changing start states. I thought this made sense as a feature now that we have start arrows, but it could lead to a situation where a DFA has more than one start state. The error handling should detect this as a possibility. Or actually, maybe it should act like in the Simulate screen where, if you're a DFA you can only toggle amongst one start state at a time.

**Comment by Necried** [comment]
The logic that performs start state checking is only done in the Simulate mode. If we are to enable creating start states in Build mode then I can have that logic applied in Build mode as well.
