### ISSUE TITLE
epsilon transitions missing

### ISSUE THREAD

**Issue by CSchank** [CSchank/finsm#11]

**Comment by Necried** [comment]
Added with #35, but pending rigorous testing and minor fixes (such as making \epsilon a reserved character)

**Comment by CSchank** [comment]
See b4f30f9679fb7ecf49affc485ccc00bb8680bc3d, cf40449f41cb143bd79ef0231a50cbd98ecdcb49, c671fab7ae5b85c238569973109412af5916cbd6, e5e3a15d3a1f73c57b87c5586668e77432f2f01f for work on epsilon transitions. 

Still tracking a bug with them and multiple transitions (#39), so I'll close this since they're implemented and we'll continue to track there.
