### ISSUE TITLE
Allow multiple data per edge label

### ISSUE THREAD

**Issue by Necried** [CSchank/finsm#19]
To have more than one transition from one state to another, the only way is to add multiple edges, which may involve dragging existing arrows out of the way so no overlap occurs. Allowing users to specify more than one transition on just one arrow may be useful and more efficient.

**Comment by CSchank** [comment]
We can detect commas and treat those as separate edges when dealing with simulations. Shouldn't be too hard but it'll take a bit of refactoring since right now if the machine has two edges it'll show two edges.

**Comment by Necried** [comment]
Implemented via commit 5cf5009976d6ca1b90dbe31ff863a4993434bcc1
