### ISSUE TITLE
snap to grid mode

### ISSUE THREAD

**Issue by CSchank** [CSchank/finsm#24]
For states, snap to a grid of say every 10 pixels. For arrows, snap to a straight line. Also, for arrows allow them to make arrows that are always directly between the two states in the x direction, and we could snap those as well. This will allow them to make arrows that are consistent with each other and states which are lined up perfectly.

**Comment by Necried** [comment]
I have no problems with this being a thing. Also, this may help when exporting to LaTeX is implemented.

**Comment by CSchank** [comment]
Implemented in 83a96dd9330cdeea2a2219eafc9006ffd003090f, along with key bindings and button. Yet to allow changing of the size via the UI, for now I think 10 is okay, but we can come back to that.
