### ISSUE TITLE
multiple transitions with `\epsilon` as one of them

### ISSUE THREAD

**Issue by CSchank** [CSchank/finsm#39]
We have to decide whether to allow this or not. If we allow it, it probably needs fixing. If we disallow it, do we put a pop-up, or just rewrite the whole thing as `\epsilon`? etc etc

**Comment by Necried** [comment]
Pop-up seems to be the way to go. See branch `warn-epsilon`

**Comment by Necried** [comment]
Work started in commit 172025361db97b527a54e59934f6a0c8d62c0cc8, and as of commit 617be1975cd2234f7b9edf379abb3a1cc698b496, the error "pop-up" is displayed in Simulate mode.
