### ISSUE TITLE
single state with epsilon self-transition doesn't stay lit up

### ISSUE THREAD

**Issue by CSchank** [CSchank/finsm#47]
![image](https://user-images.githubusercontent.com/12722104/52158655-9f258000-2668-11e9-8f72-355e0b531d4b.png)

**Comment by Necried** [comment]
Conjecture: The fact that we call `deltaHat` before checking epsilon transitions will cause self-loop states to become "cold", i.e. normal transitions will take place, and the current state will change.

Detecting epsilon self-loops during this phase should fix this issue.

**Comment by Necried** [comment]
Commit e4b2358 appears to fix this.
