### ISSUE TITLE
Simulate- Machine doesn't reset to initial start state(s) after exiting Editing tape

### ISSUE THREAD

**Issue by Necried** [CSchank/finsm#65]
Description: See title

Steps to reproduce:
1. In simulate mode, get the machine into a configuration where: current state(s) /= initial state(s)
2. Edit any tape
3. Exit editing mode. You will see that even though the tape position has reset, the start state has not.

**Comment by CSchank** [comment]
Thanks, I noticed this but failed to act on it, should be an easy fix.

**Comment by Necried** [comment]
Fixed- See #67
