### ISSUE TITLE
Keys pressed should have same behavior when caps lock is on

### ISSUE THREAD

**Issue by YoussefRizkalla** [CSchank/finsm#88]
For example, when attempting to delete a state, it currently only accepts the lower case "d". I think allowing the keys pressed events to be triggered by the same key independent of whether caps lock is on or not would present an improvement for the user experience, and allow for less confusion.

**Comment by CSchank** [comment]
Very good point - I hadn't thought of this. Easy fix, I'll keep this open until I do it!

**Comment by CSchank** [comment]
Oops, I didn't see your PR. I'll comment over there.
