### ISSUE TITLE
autosave being called when user is not logged in

### ISSUE THREAD

**Issue by CSchank** [CSchank/finsm#97]
We were seeing lots and lots of phantom saves that I couldn't explain. Turns out, if users are using the site without logging in, the client sends autosave requests every 5s which are just denied. A couple of options are to a) fix it, or b) somehow figure out a way to actually autosave even when they're not logged in, and then apply that machine to their account when they do log in. This will be trickier though and might not be what we want.

**Comment by CSchank** [comment]
This is technically terribly inefficient, but these requests are so cheap we're not noticing any practical performance penalty whatsoever serverside.

**Comment by Necried** [comment]
We can leave it as it is short-term. Long term, we just have to find a way to get the client to stop sending autosave requests when it's not logged in. Good catch @CSchank!
